# target: help - Display callable targets
.PHONY: help
help:
	@egrep "^# target:" [Mm]akefile | sed -e 's/^# target: //g' | sort

# target: clean - Clean project
.PHONY: clean
clean:
	@rm -rf build dist docs/_build
	@rm -f *.py[co]
	@rm -f *.orig
	@rm -f */*.py[co]
	@rm -f */*.orig

# target: register - Register module on PyPi
.PHONY: register
register:
	@python setup.py register

# target: upload - Upload module on PyPi
.PHONY: upload
upload:
	@python setup.py sdist upload || echo 'Upload already'
